FROM rust:slim-buster

# List of installed tools:
#  * for CycloneDDS
#     - g++
#     - cmake
#  * for zenoh-dds-plugin
#     - git
#     - clang
RUN apt-get update && apt-get -y install g++ cmake git clang wget vim
RUN apt-get -y install
COPY . .

RUN rustup update stable
RUN rustup target add arm-unknown-linux-musleabihf
RUN rustup target add i586-unknown-linux-musl
RUN git clone https://github.com/richfelker/musl-cross-make.git
RUN cd /musl-cross-make && cp config.mak.dist config.make && TARGET=arm-linux-musleabihf make && make install

#RUN cd zenoh-bridge-dds && cargo install --locked --path .